name: vscode-lean4 build

on:
  pull_request:
    branches:
    - '*'
  push:
    branches:
    - '*'

jobs:
  build-and-test:
    strategy:
      matrix:
        include:
          - name: Linux
            os: ubuntu-latest
            artifact: build-Linux release
          # - name: macOS
          #   os: macos-latest
          #   artifact: build-macOS
          - name: Windows
            os: windows-latest
            artifact: build-Windows
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
        if: matrix.os == 'windows-latest'
      - name: Build
        run: |
          npm ci
          npx lerna bootstrap --ci
          npm run build
          npx lerna run --scope=lean4 package
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          name: vscode-lean4
          path: 'vscode-lean4/lean4-*.vsix'
      - name: Lint
        run: npm run lint
      - name: Install Brew Packages
        run: |
          brew install ccache tree zstd coreutils
        if: matrix.os == 'macos-latest'
      - name: Set path to elan on Linux or macOS
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        run: |
          echo "$HOME/.elan/bin" >> $GITHUB_PATH
      - name: Set path to elan on Windows
        shell: pwsh
        if: matrix.os == 'windows-latest'
        run: |
          echo "$HOME\.elan\bin" >> $env:GITHUB_PATH
      - name: Setup elan toolchain on Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          curl -O --location https://raw.githubusercontent.com/leanprover/elan/master/elan-init.ps1
          .\elan-init.ps1 -NoPrompt 1 -DefaultToolchain leanprover/lean4:nightly
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run test
